owner: PaloAltoNetworks
repo: status.pan.dev

sites:
  - name: pan.dev
    url: https://pan.dev
  - name: xsoar.pan.dev
    url: https://xsoar.pan.dev
  - name: prisma.pan.dev
    url: https://prisma.pan.dev
  - name: panos.pan.dev
    url: https://panos.pan.dev
  - name: gallery.pan.dev
    url: https://gallery.pan.dev

status-website:
  cname: status.pan.dev
  logoUrl: https://raw.githubusercontent.com/PaloAltoNetworks/pan.dev/master/static/img/PANW_Parent_Logo_White.svg
  name: Upptime
  introTitle: "This is the status monitoring page for our family of pan.dev sites."
  navbar:
    - title: Status (pan.dev)
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
 
assignees:
  - sserrata
  - csestito
